language: c


before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis_tool.sh install_deps
  - ./travis_tool.sh install_github tdhock/PeakSegDP tdhock/PeakError

script:
  - Rscript -e "devtools::install(); source('tests/testthat.R', chdir = TRUE)"

notifications:
  email:
    on_success: change
    on_failure: change
